### ISSUE TITLE
Load and downscale images efficently

### ISSUE THREAD

**Issue by alexander255** [subliun/Antox#142]
I've sent 2 large images to my phone running Antox. Every time I open that now Antox tries to decode those images and becomes very slow then crashes with OOM error.
Please see the Android documentation for details on how to decode images in a memory-efficient manner: http://developer.android.com/training/displaying-bitmaps/load-bitmap.html

Additionally please consider loading images off the UI thread (Blocking File I/O + Linear CPU intensive tasks → very bad for UI thread, perfect for `AsyncTask`) if you haven't so already (I didn't check the code).

**Comment by subliun** [comment]
How large were the images?

**Comment by alexander255** [comment]
One was 1.6 MB and the other one was around 1.2 MB

**Comment by 00firestar00** [comment]
Decided to look into this and was able to reproduce this as well with Samsung S3 running Android 5.1.1.
Any image larger than 1MB will cause the apps memory usage to skyrocket, but viewing a chat with 2 or more images will crash the app.

memory usage for the app doubled when trying to load the images:
![image](https://cloud.githubusercontent.com/assets/3918656/9650793/efa7ebbe-51bc-11e5-86f9-f5cf80c22fab.png)

I didn't receive an OOM error, but rather this crash message:
```
09-02 21:48:50.450    9293-9293/chat.tox.antox D/ChatActivity﹕ Messages updated
09-02 21:48:50.451    9293-9293/chat.tox.antox D/ChatActivity﹕ changing chat list cursor
09-02 21:48:51.182    9293-9293/chat.tox.antox I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@c68728e time:136373463
09-02 21:48:53.070    9293-9293/chat.tox.antox I/Choreographer﹕ Skipped 48 frames!  The application may be doing too much work on its main thread.
09-02 21:49:13.114    9293-9293/chat.tox.antox E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: chat.tox.antox, PID: 9293
    java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: rx.exceptions.OnErrorNotImplementedException
            at rx.Observable$30.onError(Observable.java:7358)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: rx.exceptions.MissingBackpressureException
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:138)
            at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
            at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:51)
            at rx.Scheduler$Worker$1.call(Scheduler.java:120)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

There seems to be something weird going on. Putting in some debug logs seems like a single image is getting decoded multiple times before being cached, and then after that, is constantly hitting up the cache for the image. This would explain the memory usage being a lot higher than it should be
```
09-02 22:39:01.460    3486-3486/chat.tox.antox D/ChatActivity﹕ changing chat list cursor
09-02 22:39:01.464    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:01.478    3486-3486/chat.tox.antox D/BitmapManager﹕ Decoding Bitmap image
09-02 22:39:01.695    3486-3486/chat.tox.antox I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@2ab4d877 time:139383976
09-02 22:39:01.753    3486-3486/chat.tox.antox D/BitmapManager﹕ Decoding Bitmap image
09-02 22:39:02.243    3486-3486/chat.tox.antox D/BitmapManager﹕ Decoding Bitmap image
09-02 22:39:02.748    3486-3486/chat.tox.antox D/BitmapManager﹕ Decoding Bitmap image
09-02 22:39:02.959    3486-3902/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:03.241    3486-3486/chat.tox.antox D/BitmapManager﹕ Decoding Bitmap image
09-02 22:39:03.297    3486-3901/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:03.708    3486-3908/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:03.767    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:04.201    3486-3913/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:04.240    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:04.575    3486-3914/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:04.796    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:04.816    3486-3919/chat.tox.antox D/BitMapManager﹕ Using a sample size of 8
09-02 22:39:05.248    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:05.749    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:06.247    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:06.772    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:07.248    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:07.764    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:08.262    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:08.762    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:09.247    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:09.753    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:10.268    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:10.764    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
09-02 22:39:11.263    3486-3486/chat.tox.antox D/BitmapManager﹕ Loading Bitmap image from cache
```

**Comment by 00firestar00** [comment]
Maybe I should have waited before making my previous post... Oh well might as well have the info there. So I was able to fix this by commenting out the progressSub in GenericChatActivity ~138-144 and line 216.
This is called every 500ms to update the views in the adapter. (I assume for the progress bars if there are some) The problem is that its constantly reloading the images, and until they are fully cached it will try and decode the image. removing the progressSub related code, the images load much faster, although are still decoded twice for some reason, but at least its better than 6-10 times

Doesn't seem like it should be polling every 500ms just to update a view, especially if its only needed when an actual progress bar is present on the screen.
