### ISSUE TITLE
crash when setting profile picture from camera

### ISSUE THREAD

**Issue by txt-file** [subliun/Antox#151]
I used the option „take picture“ on the set avatar screen. After accepting the taken picture Antox crashed.

device: htc vision (htc desire z)
OS version: Cyanogen Mod 11-20150427-UNOFFICIAL-vision

**Comment by 00firestar00** [comment]
was able to reproduce on my Moto X running Cyanogen 11.
Ran out of memory trying to create the bitmap.
```
09-08 20:44:33.607    7669-7669/chat.tox.antox E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: chat.tox.antox, PID: 7669
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:708)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:633)
            at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:442)
            at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:232)
            at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:207)
            at chat.tox.antox.fragments.AvatarDialog.resizeAvatar(AvatarDialog.scala:74)
            at chat.tox.antox.fragments.AvatarDialog.onActivityResult(AvatarDialog.scala:49)
            at chat.tox.antox.activities.ProfileSettingsActivity.onActivityResult(ProfileSettingsActivity.scala:303)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3385)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3432)
            at android.app.ActivityThread.access$1300(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1253)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5179)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```
