### ISSUE TITLE
Use logger to log exceptions not System.out.err

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#163]
```
09-15 17:24:51.919  32363-32363/chat.tox.antox D/chat.tox.antox.tox.ToxSingleton﹕ Trying to bootstrap
09-15 17:24:51.919  32363-32363/chat.tox.antox W/System.err﹕ java.lang.NullPointerException
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at chat.tox.antox.tox.ToxSingleton$$anonfun$updateDhtNodes$3$$anonfun$apply$2.apply$mcVI$sp(ToxSingleton.scala:177)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at chat.tox.antox.tox.ToxSingleton$$anonfun$updateDhtNodes$3.apply(ToxSingleton.scala:176)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at chat.tox.antox.tox.ToxSingleton$$anonfun$updateDhtNodes$3.apply(ToxSingleton.scala:172)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.lang.scala.ImplicitFunctionConversions$$anon$4.call(ImplicitFunctionConversions.scala:73)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.Observable$31.onNext(Observable.java:7411)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5158)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
09-15 17:24:51.929  32363-32363/chat.tox.antox W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
```

Proper way to log exceptions is:
```
} catch (Exception e) {
Log.e/d/i(TAG, "Exception occurred while trying to... " + e.getMessage());
}
```

**Comment by wiiam** [comment]
```
Sep 11 20:16:00 <subliun>	I don't like Log.d
Sep 11 20:16:03 <subliun>	takes too long
```

**Comment by subliun** [comment]
^

**Comment by installgen2** [comment]
[06:14:27] <subliun> 'suggestion' is 'enhancement' that I don't like

**Comment by installgen2** [comment]
fuc of sublium

**Comment by installgen2** [comment]
you cuck
