### ISSUE TITLE
crash on showing messages on CM12.1

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#190]
```

 08:59:36.624 D/Antox (10920): Messages updated 
 08:59:36.626 D/Antox (10920): changing chat list cursor 
 08:59:36.644 E/CursorWindow(10920): Could not allocate CursorWindow '/data/data/chat.tox.antox/databases/ag' of size 2097152 due to error -12. 
 08:59:36.831 E/AndroidRuntime(10920): Process: chat.tox.antox,nnnn? PID: 10920 
 08:59:36.831 E/AndroidRuntime(10920): at chat.tox.antox.data.AntoxDB.keyFromString(AntoxDB.scala:358) 
 08:59:36.831 E/AndroidRuntime(10920): at chat.tox.antox.data.AntoxDB.chat$tox$antox$data$AntoxDB$$messageListFromCursor(AntoxDB.scala:385) 
 08:59:36.831 E/AndroidRuntime(10920): at chat.tox.antox.data.AntoxDB$$anonfun$10.apply(AntoxDB.scala:311) 
 08:59:36.831 E/AndroidRuntime(10920): at chat.tox.antox.data.AntoxDB$$anonfun$10.apply(AntoxDB.scala:308) 
 08:59:36.837 W/ActivityManager(459): Force finishing activity 1 chat.tox.antox/.activities.ChatActivity 
 08:59:36.846 W/ActivityManager(459): Force finishing activity 2 chat.tox.antox/.activities.MainActivity 
 08:59:37.345 W/ActivityManager(459): Activity pause timeout for ActivityRecord{10182958 u0 chat.tox.antox/.activities.ChatActivity t120 f} 
 08:59:38.195 I/WindowState(459): WIN DEATH: Window{11dcdcca u0 chat.tox.antox/chat.tox.antox.activities.MainActivity} 
 08:59:38.212 I/WindowState(459): WIN DEATH: Window{2c928304 u0 chat.tox.antox/chat.tox.antox.activities.ChatActivity} 
 08:59:38.357 I/ActivityManager(459): Process chat.tox.antox (pid 10920) has died 
 08:59:38.358 W/ActivityManager(459): Scheduling restart of crashed service chat.tox.antox/.tox.ToxService in 1000ms 
 08:59:38.368 W/PackageManager(661): Failure retrieving resources for chat.tox.antox: Resource ID #0x0 
 08:59:39.399 I/ActivityManager(459): Start proc 11047:chat.tox.antox/u0a87 for service chat.tox.antox/.tox.ToxService 
 08:59:39.560 D/:antox.tox.ToxDataFile(11047): fileName: ag 
 08:59:39.605 D/:antox.tox.ToxDataFile(11047): fileName: ag 
 08:59:39.827 D/Antox (11047): Initting ToxSingleton 
 08:59:59.376 D/Antox (11047): self connection status changed to UDP 
 09:00:14.330 D/Antox (11047): Message from: friend id: A0A9089758F2A5D4951C2F72576A1F7FCF86F50 activeKey: None chatActive: false 
 09:01:26.612 I/Timeline(923): Timeline: Activity_launch_request id:chat.tox.antox time:9754715 
 09:01:26.614 I/ActivityManager(459): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=chat.tox.antox/.activities.LoginActivity bnds=[666,852][799,1052] (has extras)} from uid 10016 on display 0 
 09:01:26.619 V/WindowManager(459): addAppToken: AppWindowToken{f22f94f token=Token{2c3687ae ActivityRecord{d45e829 u0 chat.tox.antox/.activities.LoginActivity t124}}} to stack=1 task=124 at 0 
 09:01:27.589 I/Timeline(11047): Timeline: Activity_launch_request id:chat.tox.antox time:9755691 
 09:01:27.589 I/ActivityManager(459): START u0 {cmp=chat.tox.antox/.activities.MainActivity} from uid 10087 on display 0 
 09:01:27.599 V/WindowManager(459): addAppToken: AppWindowToken{3b3fdb6b token=Token{56770ba ActivityRecord{352bdde5 u0 chat.tox.antox/.activities.MainActivity t124}}} to stack=1 task=124 at 1 
 09:01:27.909 V/WindowManager(459): Based on layer: Adding window Window{11fec347 u0 chat.tox.antox/chat.tox.antox.activities.MainActivity} at 4 of 10 
 09:01:28.739 I/ActivityManager(459): Displayed chat.tox.antox/.activities.MainActivity: +1s135ms (total +2s82ms) 
 09:01:29.175 I/Timeline(459): Timeline: Activity_windows_visible id: ActivityRecord{352bdde5 u0 chat.tox.antox/.activities.MainActivity t124} time:9757278 
 09:01:30.034 I/Timeline(11047): Timeline: Activity_launch_request id:chat.tox.antox time:9758136 
 09:01:30.035 I/ActivityManager(459): START u0 {cmp=chat.tox.antox/.activities.ChatActivity (has extras)} from uid 10087 on display 0 
 09:01:30.039 V/WindowManager(459): addAppToken: AppWindowToken{da4ce3 token=Token{11375d12 ActivityRecord{17c0e49d u0 chat.tox.antox/.activities.ChatActivity t124}}} to stack=1 task=124 at 1 
 09:01:30.200 D/Antox (11047): key = ;lkjhgasdasdasdasdsada 
 09:01:30.731 D/AntoxDB$(11047): Marked incoming messages as read 
 09:01:31.081 E/CursorWindow(11047): Could not allocate CursorWindow '/data/data/chat.tox.antox/databases/ag' of size 2097152 due to error -12. 
 09:01:31.089 E/CursorWindow(11047): Could not allocate CursorWindow '/data/data/chat.tox.antox/databases/ag' of size 2097152 due to error -12. 
 09:01:31.090 V/WindowManager(459): Adding window Window{2d4c2d99 u0 chat.tox.antox/chat.tox.antox.activities.ChatActivity} at 5 of 11 (after Window{11fec347 u0 chat.tox.antox/chat.tox.antox.activities.MainActivity}) 
 09:01:31.281 E/AndroidRuntime(11047): Process: chat.tox.antox, PID: 11047 
 09:01:31.281 E/AndroidRuntime(11047): at chat.tox.antox.data.AntoxDB.keyFromString(AntoxDB.scala:358) 
 09:01:31.281 E/AndroidRuntime(11047): at chat.tox.antox.data.AntoxDB.chat$tox$antox$data$AntoxDB$$messageListFromCursor(AntoxDB.scala:385) 
 09:01:31.281 E/AndroidRuntime(11047): at chat.tox.antox.data.AntoxDB$$anonfun$messageListObservable$1.apply(AntoxDB.scala:325) 
 09:01:31.281 E/AndroidRuntime(11047): at chat.tox.antox.data.AntoxDB$$anonfun$messageListObservable$1.apply(AntoxDB.scala:324) 
 09:01:31.285 W/ActivityManager(459): Force finishing activity 1 chat.tox.antox/.activities.ChatActivity 
 09:01:31.290 W/ActivityManager(459): Force finishing activity 2 chat.tox.antox/.activities.MainActivity 
 09:01:31.790 W/ActivityManager(459): Activity pause timeout for ActivityRecord{17c0e49d u0 chat.tox.antox/.activities.ChatActivity t124 f} 
 09:01:32.414 I/WindowState(459): WIN DEATH: Window{11fec347 u0 chat.tox.antox/chat.tox.antox.activities.MainActivity} 
 09:01:32.425 I/WindowState(459): WIN DEATH: Window{2d4c2d99 u0 chat.tox.antox/chat.tox.antox.activities.ChatActivity} 
 09:01:32.657 I/ActivityManager(459): Process chat.tox.antox (pid 11047) has died 
 09:01:32.658 W/ActivityManager(459): Service crashed 2 times, stopping: ServiceRecord{7794a0e u0 chat.tox.antox/.tox.ToxService} 
 09:01:32.809 W/PackageManager(661): Failure retrieving resources for chat.tox.antox: Resource ID #0x0 
 09:01:45.986 I/Timeline(923): Timeline: Activity_launch_request id:chat.tox.antox time:9774088 
 09:01:45.986 I/ActivityManager(459): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=chat.tox.antox/.activities.LoginActivity bnds=[666,852][799,1052] (has extras)} from uid 10016 on display 0 
 09:01:45.991 V/WindowManager(459): addAppToken: AppWindowToken{1bf3bc58 token=Token{2d1dbd3b ActivityRecord{2f8b77ca u0 chat.tox.antox/.activities.LoginActivity t125}}} to stack=1 task=125 at 0 
 09:01:46.095 I/ActivityManager(459): Start proc 11571:chat.tox.antox/u0a87 for activity chat.tox.antox/.activities.LoginActivity 
 09:01:47.236 I/Timeline(11571): Timeline: Activity_launch_request id:chat.tox.antox time:9775339 
 09:01:47.237 I/ActivityManager(459): START u0 {cmp=chat.tox.antox/.activities.MainActivity} from uid 10087 on display 0 
 09:01:47.244 V/WindowManager(459): addAppToken: AppWindowToken{38b465e9 token=Token{3891be70 ActivityRecord{16b898b3 u0 chat.tox.antox/.activities.MainActivity t125}}} to stack=1 task=125 at 1 
 09:01:47.264 D/:antox.tox.ToxDataFile(11571): fileName: ag 
 09:01:47.329 D/:antox.tox.ToxDataFile(11571): fileName: ag 
 09:01:47.636 D/Antox (11571): Initting ToxSingleton 
 09:01:47.933 V/WindowManager(459): Based on layer: Adding window Window{
```

**Comment by agilob** [comment]
1. receive message when antox works in background
2. open antox
3. open recent chat with the new message
4. happens always

didn't happen before upgrade from android 4.4.4, started happening after upgrade to android 5.1 (CM 12.1), nexus 7

**Comment by subliun** [comment]
The db has really been having some trouble lately huh. :-/
