### ISSUE TITLE
App crashes when starting Tox connection

### ISSUE THREAD

**Issue by wiiam** [subliun/Antox#229]
logcat output:
```
12-20 10:42:49.502 6542-6542/chat.tox.antox E/art: dlopen("/data/app/chat.tox.antox-1/lib/arm/libtox4j.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "libtox4j.so"...
12-20 10:44:44.742 6542-6542/chat.tox.antox E/art: dlopen("/data/data/chat.tox.antox/cache/tox4j828032143libtox4j.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "tox4j828032143libtox4j.so"...
12-20 10:44:44.766 6542-6542/chat.tox.antox D/AndroidRuntime: Shutting down VM
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime: FATAL EXCEPTION: main
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime: Process: chat.tox.antox, PID: 6542
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "tox4j828032143libtox4j.so"...
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at java.lang.Runtime.load(Runtime.java:331)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at java.lang.System.load(System.java:981)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$$anonfun$loadFromWeb$1.apply(ToxLoadJniLibrary.scala:80)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$$anonfun$loadFromWeb$1.apply(ToxLoadJniLibrary.scala:72)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.withTempFile(ToxLoadJniLibrary.scala:57)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.loadFromWeb(ToxLoadJniLibrary.scala:72)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.load(ToxLoadJniLibrary.scala:111)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxLoadJniLibrary.load(ToxLoadJniLibrary.scala)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxCoreJni.<clinit>(ToxCoreJni.java:11)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at im.tox.tox4j.impl.jni.ToxCoreImpl.<init>(ToxCoreImpl.scala:79)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.activities.CreateAccountActivity.loadToxData(CreateAccountActivity.scala:118)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.activities.CreateAccountActivity.createAccount(CreateAccountActivity.scala:217)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.activities.CreateAccountActivity.onImportFileSelected(CreateAccountActivity.scala:330)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.activities.CreateAccountActivity$$anon$2.fileSelected(CreateAccountActivity.scala:304)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.FileDialog$$anon$3.fireEvent(FileDialog.scala:103)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.FileDialog$$anon$3.fireEvent(FileDialog.scala:100)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.ListenerList$$anonfun$fireEvent$1.apply(FileDialog.scala:204)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.ListenerList$$anonfun$fireEvent$1.apply(FileDialog.scala:203)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at scala.collection.Iterator$class.foreach(Iterator.scala:742)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.ListenerList.fireEvent(FileDialog.scala:203)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.FileDialog.chat$tox$antox$transfer$FileDialog$$fireFileSelectedEvent(FileDialog.scala:100)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at chat.tox.antox.transfer.FileDialog$$anon$2.onClick(FileDialog.scala:80)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.widget.AdapterView.performItemClick(AdapterView.java:305)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.widget.AbsListView$3.run(AbsListView.java:3866)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
12-20 10:44:44.767 6542-6542/chat.tox.antox E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by HongyuGong** [comment]
I have met this problem. In fact, you need to set the API level as 23 when compiling it. If you test it on phones, its Android level is expected to be no lower than 4.4.2.
