### ISSUE TITLE
Crash after updating to 0.22

### ISSUE THREAD

**Issue by zetok** [subliun/Antox#41]
```
04-30 18:55:53.260 I/ActivityManager(2256): Displayed im.tox.antoxnightly/im.tox.antox.activities.MainActivity: +1s221ms
04-30 18:55:53.260 I/Timeline(2256): Timeline: Activity_windows_visible id: ActivityRecord{4267e7a0 u0 im.tox.antoxnightly/im.tox.antox.activities.MainActivity t110} time:1572412537
04-30 18:55:53.265 W/Binder  (2561): Caught a RuntimeException from the binder stub implementation.
04-30 18:55:53.265 W/Binder  (2561): java.lang.NullPointerException
04-30 18:55:53.265 W/Binder  (2561): 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
04-30 18:55:53.265 W/Binder  (2561): 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
04-30 18:55:53.265 W/Binder  (2561): 	at android.os.Binder.execTransact(Binder.java:404)
04-30 18:55:53.265 W/Binder  (2561): 	at dalvik.system.NativeStart.run(Native Method)
```
No idea what caused it.

Aside from crash, it was strange that Antox didn't display contact being online, even though contact saw Antox being online.

**Comment by zetok** [comment]
Hm, another crash from that log, shortly before first one:
```
04-30 18:55:50.305 D/AndroidRuntime(13975): Shutting down VM
04-30 18:55:50.305 W/dalvikvm(13975): threadid=1: thread exiting with uncaught exception (group=0x41a09ce0)
04-30 18:55:50.310 E/AndroidRuntime(13975): FATAL EXCEPTION: main
04-30 18:55:50.310 E/AndroidRuntime(13975): Process: im.tox.antoxnightly, PID: 13975
04-30 18:55:50.310 E/AndroidRuntime(13975): java.util.NoSuchElementException: None.get
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at scala.None$.get(Option.scala:344)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at scala.None$.get(Option.scala:342)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at im.tox.antox.activities.ChatActivity$$anon$4.onClick(ChatActivity.scala:96)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.view.View.performClick(View.java:4445)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.view.View$PerformClick.run(View.java:18446)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.os.Handler.handleCallback(Handler.java:733)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.os.Looper.loop(Looper.java:136)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
04-30 18:55:50.310 E/AndroidRuntime(13975): 	at dalvik.system.NativeStart.main(Native Method)
04-30 18:55:50.340 W/ActivityManager(2256):   Force finishing activity im.tox.antoxnightly/im.tox.antox.activities.ChatActivity
```

**Comment by subliun** [comment]
I can't reproduce his without more information. please reopen if it happens again.
